### ISSUE TITLE
EventStore data not persisted to the DB

### ISSUE THREAD

**Issue by lawrenceong001** [mizrael/SuperSafeBank#1] opened 2020-08-14 15:41 UTC
hello Davide,

I have been playing with your project (thanks by the way!) and am quite impressed with how things are built. I'm able to create customers and accounts. as well, it appears I can initiate a deposit (haven't tried withdrawal) as well, all of which comes back successful. 

one thing, however, was the the deposits does not seem to update the balance in the mongo database. I'm able to see the customer and account information though, once they are created. 

here are some things I've done:

1. cloned the repo
2. executed `docker-compose up` to load all required images.
  1. note that I had to specify 5.0.8 on eventstore to allow accessing the UI without https
  2. for my particular implementation, I also disabled mongodb so I can have an instance of the database server locally
3. opened project in VS 2019, 
  1. set the project start to both applications (web api and notifications)
  2. removed https from the web api

am I missing something here? 

thanks in advance.

**Comment by mizrael** [comment] 2020-08-14 15:52
hi, thank you very much for your comment! Just to confirm, have you tried running the test suite?
Honestly, I haven't touched that codebase in a while now, although I'm planning of converting all the persistence layers to Azure.
Anyways, I'll go over the steps you've outlined and get back to you as soon as possible!

**Comment by mizrael** [comment] 2020-08-14 16:39
I think I spotted the root cause, actually both of them:
- MongoDb was storing the balance as string instead of decimal (fixed with https://github.com/mizrael/SuperSafeBank/commit/9978f5e43cc125ca566a851b29f73e384deea4b5 ) 
- logging was not configured properly ( https://github.com/mizrael/SuperSafeBank/commit/3ffa4ba0de2d2144752d6bec9790affa4c03d59d )

let me know if it works now!

**Comment by lawrenceong001** [comment] 2020-08-14 17:28
> 
> 
> I think I spotted the root cause, actually both of them:
> 
>     * MongoDb was storing the balance as string instead of decimal (fixed with [9978f5e](https://github.com/mizrael/SuperSafeBank/commit/9978f5e43cc125ca566a851b29f73e384deea4b5) )
> 
>     * logging was not configured properly ( [3ffa4ba](https://github.com/mizrael/SuperSafeBank/commit/3ffa4ba0de2d2144752d6bec9790affa4c03d59d) )
> 
> 
> let me know if it works now!

hi @mizrael -- yes the totals update now! thanks for your help. regarding your plan to migrate this to Azure, are you planning to use the event hub instead of eventstore+Kafka+zookeeper? 

tks again.

**Comment by mizrael** [comment] 2020-08-14 17:42
glad it worked!
I'll probably move to a combination of Event Hub and either CosmosDB or simply Storage Tables, still have to pick a side.

**Comment by lawrenceong001** [comment] 2020-08-14 18:10
> 
> 
> glad it worked!
> I'll probably move to a combination of Event Hub and either CosmosDB or simply Storage Tables, still have to pick a side.

tks @mizrael. that's also that the path we will be taking for one of my projects! would be very interested in seeing your plans for migration. just out of curiosity, are there any compelling reasons to move off of eventstore+kafka?

**Comment by mizrael** [comment] 2020-08-14 18:14
No real compelling reason. I was planning of building a simple UI with Blazor and wanted to host everything somewhere. At this point making use of what Azure makes available seems the right thing to do. I don't want to deal too much with infrastructure-related issues :)

**Comment by lawrenceong001** [comment] 2020-08-14 19:47
> 
> 
> No real compelling reason. I was planning of building a simple UI with Blazor and wanted to host everything somewhere. At this point making use of what Azure makes available seems the right thing to do. I don't want to deal too much with infrastructure-related issues :)

ok -- that's cool then. i'm still sorting through the code to understand the pattern you've implemented better. can you tell me if i have the sequence correct:

1. web api sends command
2. command pushes to kafka
3. kafka pushes to eventstore
4. kafka pushes to mongodb


tks

**Comment by mizrael** [comment] 2020-08-15 00:31
no, it's more like this:
1. web API controller receives REST request
2. web API builds command and sends it to commands bus (eg. MediatR)
3. command handler loads the aggregate and performs the operation 
4. command handler persists the aggregate in Eventstore
5. Eventstore repository stores the aggregate's domain events and pushes integration events on the integration bus ( Kafka )
6. a subscriber picks up the event and updates the query DB (Mongo). The fact that in this solution the subscriber is in the same project as the web API is just a matter of taste. Another option would be hosting in a different service, running in the background

hope this helps!

**Comment by lawrenceong001** [comment] 2020-08-15 04:52
> 
> 
> no, it's more like this:
> 
>     1. web API controller receives REST request
> 
>     2. web API builds command and sends it to commands bus (eg. MediatR)
> 
>     3. command handler loads the aggregate and performs the operation
> 
>     4. command handler persists the aggregate in Eventstore
> 
>     5. Eventstore repository stores the aggregate's domain events and pushes integration events on the integration bus ( Kafka )
> 
>     6. a subscriber picks up the event and updates the query DB (Mongo). The fact that in this solution the subscriber is in the same project as the web API is just a matter of taste. Another option would be hosting in a different service, running in the background
> 
> 
> hope this helps!

yes it does -- thanks Davide!

i was thinking the same thing about the subscriber -- its lifecycle would be quite different from the api such that it would be better off running indepedently

tks

**Closed** 2020-08-18 15:01 UTC

**Comment by lawrenceong001** [comment] 2020-08-18 19:16
> 
> 
> no, it's more like this:
> 
>     1. web API controller receives REST request
> 
>     2. web API builds command and sends it to commands bus (eg. MediatR)
> 
>     3. command handler loads the aggregate and performs the operation
> 
>     4. command handler persists the aggregate in Eventstore
> 
>     5. Eventstore repository stores the aggregate's domain events and pushes integration events on the integration bus ( Kafka )
> 
>     6. a subscriber picks up the event and updates the query DB (Mongo). The fact that in this solution the subscriber is in the same project as the web API is just a matter of taste. Another option would be hosting in a different service, running in the background
> 
> 
> hope this helps!

hi again Davide, 

I have a question regarding this, hopefully you can help. in the description above, you had the command handler store the event in the event repository before sending the message to kafka. is that preferable over having the command handler send the message to kafka, and then having a subscriber take that and persist to event store? 

tks
Lawrence

**Comment by mizrael** [comment] 2020-08-18 20:28
hi again Lawrence :)

you can totally do it, especially if the command handler execution takes too much time. This would switch to a completely async process, allowing command execution in the background without blocking the caller.

The only drawback is that you don't have immediate validation/error checking, unless you specifically add it before the command execution.

**Comment by lawrenceong001** [comment] 2020-08-19 15:08
> 
> 
> hi again Lawrence :)
> 
> you can totally do it, especially if the command handler execution takes too much time. This would switch to a completely async process, allowing command execution in the background without blocking the caller.
> 
> The only drawback is that you don't have immediate validation/error checking, unless you specifically add it before the command execution.

tks Davide, 

I was asking about this because if you were to apply this to azure, i'm assuming the event is first pushed to the event hub, where a "listener" will then process and push further down to CosmosDB. 

as well, in this diagram i recreated from Vaughn Vernon's book about event sourcing:


                                                                          +--------+       
    +-----------------+            +-----------------+         #2    ------ Event  |       
    |                 |    #1      |                 |     ---------/     +--------+       
    |     Client      --------------    Aggregate    -----/         +--------+ +---------+ 
    |                 |            |                 |              | Event  | |  Event  | 
    +--------|--------+            +-----------------+              +--------+ +---/-----+ 
             |                                                                    |        
             |                                                                    /        
             |                                                                   /         
             | #6                                                               / #3       
             |                                                                 |           
             |                                                                 /           
             |                                                     +----------|-----------+
    +--------|--------+            +-----------------+             |                      |
    |                 |     #5     |                 |       #4    |    Event Persist     |
    |   Repository    --------------    Event Store  ---------------      Subscriber      |
    |                 |            |                 |             |                      |
    +-----------------+            +-----------------+             +----------------------+

the group of events between #2 and #3 seems to indicate some kind of a bus that can sequentially manage them. 

interestingly, this (link)[https://medium.com/@bawa.simar/building-microservices-by-applying-ddd-cqrs-and-event-sourcing-on-axon-java-sprint-boot-platform-2e12289b8a2b] also appears to support doing both at the same time. 

tks again,
Lawrence

**Comment by mizrael** [comment] 2020-08-19 15:12
that's super interesting. I'm planning the porting to Azure these days (if you've noticed, I started cleaning up and refactoring the solution a lot). I'll keep you posted as soon as I come up with the design.

Thanks!

**Comment by lawrenceong001** [comment] 2020-08-19 16:41
> 
> 
> that's super interesting. I'm planning the porting to Azure these days (if you've noticed, I started cleaning up and refactoring the solution a lot). I'll keep you posted as soon as I come up with the design.
> 
> Thanks!

Great to know Davide! I wonder if the azure port could be a separate project as what you have here is a functioning non-cloud sample that people like me found very useful in understanding how concepts are applied. 

look forward to your design Davide. 

tks
Lawrence

**Comment by mizrael** [comment] 2020-08-19 16:47
> Great to know Davide! I wonder if the azure port could be a separate project as what you have here is a functioning non-cloud sample that people like me found very useful in understanding how concepts are applied.

Yes, that's the plan: I'm adding a separate project and using conditionals based on compilation symbols to switch from non-cloud to Azure :)

**Comment by lawrenceong001** [comment] 2020-08-19 16:54
> 
> 
> > Great to know Davide! I wonder if the azure port could be a separate project as what you have here is a functioning non-cloud sample that people like me found very useful in understanding how concepts are applied.
> 
> Yes, that's the plan: I'm adding a separate project and using conditionals based on compilation symbols to switch from non-cloud to Azure :)

ok that's good to know Davide, 

I myself am following that path you're on -- i intended to design an all-local dev system, which will switch to Azure native services (which will also include running the APIs in Azure Service Fabric) in the final phase of the implementation. 

tks
Lawrence
